# nelmio_cors:
#     defaults:
#         allow_credentials: true
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         #allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE','OPTIONS', 'PATCH']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/':
#             allow_origin: ['http://localhost:3000']
#             # allow_headers: ['Content-Type', 'Authorization']
#             # allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#             # allow_credentials: true
nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/': ~
